name: Dmitriy Shibarshin
pygments: rogue
description: Dmitriy Shibarshin
url: http://shibarsh.in/
analytics :
  provider : google
  google :
      tracking_id : 'UA-41805851-1'
  getclicky :
    site_id :
